name: auroim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^3.1.0
  auto_size_text: ^2.1.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  chewie: ^1.2.2
  connectivity: ^3.0.6
  country_code_picker: null
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dotted_line: ^3.0.0
  dropdown_date_picker: 0.1.1+2
  expandable: ^5.0.1
  file_picker: ^3.0.3
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  flutter_arc_text: ^0.5.0
  flutter_page_indicator: ^0.0.3
  flutter_rating_bar: null
  flutter_screenutil: ^5.0.0+2
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_typeahead: ^3.1.3
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  google_sign_in: ^5.0.4
  gradient_text: ^1.0.2
  horizontal_data_table: ^3.4.1
  http: ^0.13.3
  http_auth: ^1.0.0
  international_phone_input: ^1.0.4
  intl: ^0.17.0
  keyboard_visibility: ^0.5.6
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  provider: ^5.0.0
  screen: ^0.0.5
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  super_tooltip: ^1.0.1
  syncfusion_flutter_charts: ^19.1.69+1
  timeago: ^3.1.0
  toast: ^0.1.5
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.6
  video_player: ^2.1.6
  webview_flutter: ^2.0.8
  youtube_player_flutter: ^8.0.0
#  flutter_facebook_login:
#    git:
#      url: https://github.com/roughike/flutter_facebook_login
#      ref: '79ff08a'
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Scheherazade
      fonts:
        - asset: fonts/Scheherazade-Regular.ttf
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu-Regular.ttf

    - family: Rosarivo
      fonts:
        - asset: fonts/Rosarivo-Regular.ttf
    - family: RosarioMedium
      fonts:
        - asset: fonts/Rosario-Medium.ttf
    - family: RosarioRegular
      fonts:
        - asset: fonts/Rosario-Regular.ttf
    - family: RosarioSemiBold
      fonts:
        - asset: fonts/Rosario-SemiBold.ttf
    - family: RosarioBold
      fonts:
        - asset: fonts/Rosario-Bold.ttf
    - family: Rasa
      fonts:
        - asset: fonts/Rasa-Light.ttf
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
